### ISSUE TITLE
[bug]: ente.dev mirrors are timing out

### ISSUE THREAD

**Issue by T145** [WilliDieEnte/BetterBlocklist#11]
Presently, the ente.dev mirrors are down, and seem to have been so for a couple days. Guessing Cloudflare config changes might be to blame?

**Comment by WilliDieEnte** [comment]
Heya, firstly, sorry for the downtime!
I've been aware of the issue, but the last few weeks have unfortunately been very stressful for me.
I, as well as many others as I recently learned, have been having issues with NginxProxyManager and both of my reverse proxies were running it.
Due to that, both were affected by the same bug and went down, hooray!

Now the reverse proxies are diversified, and all server VMs are running in a High-Availability Proxmox Cluster with Ceph.
Also as a last resort I'll be setting up a co-location as fallback in the next few days just in case anything happens.
Will keep you updated in #10 ^-^

Last, but not least, I'm sorry for the silence, that won't happen again.
