### ISSUE TITLE
FALSE - *.com

### ISSUE THREAD

**Issue by gatisluck** [WilliDieEnte/BetterBlocklist#12]
**Affected Domain(s)**
*.com

**From Blocklist**
Suspicious
Advertising

**Additional context**
These two blocklist started blocking all .com domains eg. github.com, youtube.com, google.com etc.

**Comment by WilliDieEnte** [comment]
That's what happens when you let your crawlers run rampant and don't monitor them properly - that's on me c.c
Sorry for the inconvenience!
I've improved them and added a few checks and additional regex rules to make sure they only catch valid domains, as my crawler has previously read any href tag without sanitizing it properly.
Also, it'll not include direct IP-Addresses as they are useless for "normal" AdGuard/Pi-Hole/uBlock/... instances, but maybe worth making a list for in the future .-.
If you have any improvements to share, feel free to, I'd appreciate it greatly, and thank you for taking the time to report it in the first place ^w^

**Comment by WilliDieEnte** [comment]
Also rewritten part of the processing in general, it _should_ work as previously, while only using about two thirds of the CPU time, I couldn't find any issues in my limited testing, let's just push to prod and hope it'll all go well lol
